name: Deploy to Production

on:
  push:
    branches:
      - feature/deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Start
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.actor }}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_DEPLOYMENT_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_ADMIN_ID }} \
          -d text="⏳ <b>Начался деплой AI Legal Assistant</b>%0A%0A👤 От: $AUTHOR%0A📝 Коммит: <i>$COMMIT_MSG</i>" \
          -d parse_mode=HTML

      - name: Git Pull and Reset
        run: |
          cd /home/stanislav/hacaton/AI_Legal_Assistant
          git fetch
          git checkout feature/deploy
          git reset --hard origin/feature/deploy

      - name: Create .env file
        run: |
          cd /home/stanislav/hacaton/AI_Legal_Assistant/backend
          
          echo "# Generated by GitHub Actions" > .env
          echo "# Boris, Hi!" > .env
          
          echo "EMBEDDINGS_MODEL=intfloat/multilingual-e5-large" >> .env
          
          echo "GEMINI_MODEL=gemini-2.5-flash" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "GEMINI_BASE_URL=https://still-limit-741c.s-markovtsev.workers.dev" >> .env
          echo "GEMINI_TIMEOUT_SECONDS=30" >> .env
          
          echo "TOP_K=7" >> .env
          
          echo "HF=${{ secrets.HF_TOKEN }}" >> .env
          
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=db-backend" >> .env
          echo "POSTGRES_PORT=6432" >> .env
          echo "POSTGRES_DB=hackathon_db" >> .env

      - name: Restart Docker
        run: |
          cd /home/stanislav/hacaton/AI_Legal_Assistant
          docker compose up -d --build --force-recreate
          docker image prune -f

      - name: Notify Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_DEPLOYMENT_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_ADMIN_ID }} \
          -d text="✅ <b>AI Legal Assistant успешно обновлен!</b>%0AВсе сервисы перезапущены." \
          -d parse_mode=HTML

      - name: Notify Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_DEPLOYMENT_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_ADMIN_ID }} \
          -d text="❌ <b>Ошибка деплоя AI Legal Assistant!</b>%0AПроверь логи сборки в GitHub Actions или на сервере." \
          -d parse_mode=HTML
